
all:

include ../kaldi.mk

EXTRA_CXXFLAGS += -Wno-sign-compare
#-DDEBUG_SPEED
#-DDEBUG_PRINT

OBJFILES = fst-convert-openfst.o tf-2-kaldi-api.o

LIBNAME = chain-loss

TESTFILES = chain-loss-test

ADDLIBS = ../nnet3/kaldi-nnet3.a ../chain/kaldi-chain.a ../cudamatrix/kaldi-cudamatrix.a \
		  ../decoder/kaldi-decoder.a ../lat/kaldi-lat.a \
		  ../fstext/kaldi-fstext.a ../hmm/kaldi-hmm.a \
		  ../transform/kaldi-transform.a ../gmm/kaldi-gmm.a \
		  ../tree/kaldi-tree.a ../util/kaldi-util.a ../matrix/kaldi-matrix.a \
		  ../base/kaldi-base.a 

include ../makefiles/default_rules.mk



